language: go
services:
  - postgresql
addons:
  postgresql: "9.4"
go:
    - 1.6
    - 1.7.x
    - master
install:
    - go get github.com/Masterminds/glide
    - glide install
before_script:
  - cp .travis.database.yml database.yml
  - psql -c 'create database jsonb_test;' -U postgres
  - psql -c "CREATE USER jsonb_user WITH PASSWORD 'jsonb_pass';" -U postgres
  - psql -c 'CREATE TABLE "test" ("id" serial,"field" jsonb,PRIMARY KEY ("id"));' -U postgres -djsonb_test
  - psql -c 'GRANT ALL ON SEQUENCE public.test_id_seq TO jsonb_user; GRANT ALL ON TABLE public.test TO jsonb_user;' -U postgres -djsonb_test
script:
    - go test -v $(glide nv)
matrix:
  allow_failures:
    - go: master